version: '3.8'
services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local


