services:
  app:
    container_name: app
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env.defaults
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.defaults

volumes:
  db:
    driver: local
