"""data integrity fk indexes composite pk not null user timestamps

Revision ID: 9be7780250e1
Revises: d2fc6ee17305
Create Date: 2026-08-13 11:47:34.141617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9be7780250e1'
down_revision: Union[str, None] = 'd2fc6ee17305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('body_parts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('body_parts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'target_body_part_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'exercise_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('exercises_exercise_type_id_idx'), 'exercises', ['exercise_type_id'], unique=False)
    op.create_index(op.f('exercises_level_id_idx'), 'exercises', ['level_id'], unique=False)
    op.create_index(op.f('exercises_owner_id_idx'), 'exercises', ['owner_id'], unique=False)
    op.create_index(op.f('exercises_target_body_part_id_idx'), 'exercises', ['target_body_part_id'], unique=False)
    op.alter_column('levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('levels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_plan_training_unit', 'training_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_plan_training_unit', 'training_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # H6: give the association table a composite primary key so duplicate and
    # (NULL, NULL) (plan, unit) rows are rejected at the database level.
    op.create_primary_key(
        "training_plan_training_unit_pkey",
        "training_plan_training_unit",
        ["training_plan_id", "training_unit_id"],
    )
    op.alter_column('training_plans', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('training_plans_owner_id_idx'), 'training_plans', ['owner_id'], unique=False)
    op.alter_column('training_units', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training_units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_units', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('training_units_owner_id_idx'), 'training_units', ['owner_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_full_name_idx'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('users_id_idx'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_id_idx'), table_name='users')
    op.drop_index(op.f('users_full_name_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('training_units_owner_id_idx'), table_name='training_units')
    op.alter_column('training_units', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_units', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('training_plans_owner_id_idx'), table_name='training_plans')
    op.alter_column('training_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('training_plans', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(
        "training_plan_training_unit_pkey",
        "training_plan_training_unit",
        type_="primary",
    )
    op.alter_column('training_plan_training_unit', 'training_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training_plan_training_unit', 'training_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('levels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('exercises_target_body_part_id_idx'), table_name='exercises')
    op.drop_index(op.f('exercises_owner_id_idx'), table_name='exercises')
    op.drop_index(op.f('exercises_level_id_idx'), table_name='exercises')
    op.drop_index(op.f('exercises_exercise_type_id_idx'), table_name='exercises')
    op.alter_column('exercises', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'exercise_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'target_body_part_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercise_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('body_parts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('body_parts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###