"""empty message

Revision ID: a89cffb43d42
Revises: 2a0e92747c9c
Create Date: 2023-11-21 20:47:50.325103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89cffb43d42'
down_revision: Union[str, None] = '2a0e92747c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index('ix_body_parts_key', table_name='body_parts')
    op.drop_column('body_parts', 'key')
    op.drop_index('ix_exercise_types_key', table_name='exercise_types')
    op.drop_column('exercise_types', 'key')
    op.add_column('exercises', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index('ix_exercises_key', table_name='exercises')
    op.create_foreign_key(None, 'exercises', 'users', ['owner_id'], ['id'])
    op.drop_column('exercises', 'key')
    op.drop_index('ix_levels_key', table_name='levels')
    op.drop_column('levels', 'key')
    op.add_column('training_plans', sa.Column('description', sa.String(), nullable=True))
    op.add_column('training_plans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('training_plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('training_plans', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index('ix_training_plans_key', table_name='training_plans')
    op.create_foreign_key(None, 'training_plans', 'users', ['owner_id'], ['id'])
    op.drop_column('training_plans', 'key')
    op.drop_column('training_plans', 'numer_of_training_units')
    op.add_column('training_units', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('training_units', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('training_units', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('training_units_key_key', 'training_units', type_='unique')
    op.create_foreign_key(None, 'training_units', 'users', ['owner_id'], ['id'])
    op.drop_column('training_units', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_units', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'training_units', type_='foreignkey')
    op.create_unique_constraint('training_units_key_key', 'training_units', ['key'])
    op.drop_column('training_units', 'owner_id')
    op.drop_column('training_units', 'updated_at')
    op.drop_column('training_units', 'created_at')
    op.add_column('training_plans', sa.Column('numer_of_training_units', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('training_plans', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training_plans', type_='foreignkey')
    op.create_index('ix_training_plans_key', 'training_plans', ['key'], unique=False)
    op.drop_column('training_plans', 'owner_id')
    op.drop_column('training_plans', 'updated_at')
    op.drop_column('training_plans', 'created_at')
    op.drop_column('training_plans', 'description')
    op.add_column('levels', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_levels_key', 'levels', ['key'], unique=False)
    op.add_column('exercises', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_index('ix_exercises_key', 'exercises', ['key'], unique=False)
    op.drop_column('exercises', 'owner_id')
    op.add_column('exercise_types', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_exercise_types_key', 'exercise_types', ['key'], unique=False)
    op.add_column('body_parts', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_body_parts_key', 'body_parts', ['key'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
