"""make names unique=True

Revision ID: c64568c0f916
Revises: a89cffb43d42
Create Date: 2023-12-03 15:55:49.053181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c64568c0f916"
down_revision: Union[str, None] = "a89cffb43d42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "exercises", ["name"])
    op.create_unique_constraint(None, "levels", ["name"])
    op.alter_column(
        "training_plans", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("training_plans", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(None, "levels", type_="unique")
    op.drop_constraint(None, "exercises", type_="unique")
    # ### end Alembic commands ###
